### ISSUE TITLE
AbstractDifferentiation stable docs 404

### ISSUE THREAD

**Issue by Qfl3x** [JuliaDiff/AbstractDifferentiation.jl#113]
https://juliadiff.org/AbstractDifferentiation.jl/stable

Gives a 404 error

**Comment by devmotion** [comment]
That's expected. Stable docs are only built when a new release is tagged, and there hasn't been a new release since the doc website was added. This will be fixed automatically once the next release is made (but this might take a few days since it will be a breaking release and we might want to include more breaking changes).
