### ISSUE TITLE
New version timeline

### ISSUE THREAD

**Issue by mohamed82008** [JuliaDiff/AbstractDifferentiation.jl#116]
The current master branch is already in a better shape that the last release. What do you all think of making a new release now and then doing another (breaking) release later if needed?

**Comment by pkofod** [comment]
I tried adding support in NLSolvers using an extension, but only forwarddiff seemed to work all the way through. Master does work though, so I'm in favor!

**Comment by gdalle** [comment]
I wanted to solve #53 before, since it's a very breaking change

**Comment by gdalle** [comment]
On it now

**Comment by gdalle** [comment]
Fine with that too

**Comment by mohamed82008** [comment]
Thanks @gdalle and @devmotion, closing this issue now.

**Comment by gdalle** [comment]
https://github.com/JuliaRegistries/General/pull/93288

**Comment by gdalle** [comment]
The stable docs wasn't built, probably because the CI was configured back when there was no docs website. I tried [pushing a new tag](https://documenter.juliadocs.org/stable/man/hosting/#Fixing-broken-release-deployments) but to no avail.
I thought the `push` syntax included tags as workflow triggers, but perhaps we need to [specify that explcitly](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-workflow-only-when-a-push-of-specific-tags-occurs)?

**Comment by ToucheSir** [comment]
> but perhaps we need to [specify that explcitly](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-workflow-only-when-a-push-of-specific-tags-occurs)?

Yes, see e.g. https://github.com/hyrodium/PkgTemplates.jl/blob/47aa85f0247dc5d2a695f97efcc245c37e414325/templates/github/workflows/CI.yml#L8.

**Comment by gdalle** [comment]
Working now
