### ISSUE TITLE
Code inside function with rrule should not run

### ISSUE THREAD

**Issue by gaurav-arya** [JuliaDiff/AbstractDifferentiation.jl#57]
MWE:

```
using Zygote
import ChainRulesCore.rrule
using ChainRulesCore: NoTangent
using AbstractDifferentiation

function myfunc(x)
    println("This should not print if I have an rrule.")
    x
end

rrule(::typeof(myfunc), x) = (x, (y -> (NoTangent(), y)))

println("Zygote run:")
Zygote.gradient(myfunc, 1) # nothing prints
println("AD run:")
AD.derivative(AD.ZygoteBackend(), myfunc, 1) # something prints
```
The code inside of myfunc should never run. In addition to possible inefficiency, this may lead to incorrect/confusing results for stateful functions or stochastic functions.

**Comment by devmotion** [comment]
My hypothesis (without checking it in detail) is that the problem is that the backend for ChainRulesCore integration (used also for Zygote in your example) uses the `rrule` to define the pullback function (https://github.com/JuliaDiff/AbstractDifferentiation.jl/blob/12a0e27d0f54e6300b725dfb9dafc21ef507b724/src/ruleconfig.jl#L10) but does drop the value of the primal completely, which therefore has to be recovered from the original function in `value_and_pullback_function` (https://github.com/JuliaDiff/AbstractDifferentiation.jl/blob/12a0e27d0f54e6300b725dfb9dafc21ef507b724/src/AbstractDifferentiation.jl#L248) which is e.g. used by `derivative` (https://github.com/JuliaDiff/AbstractDifferentiation.jl/blob/12a0e27d0f54e6300b725dfb9dafc21ef507b724/src/AbstractDifferentiation.jl#L38) via `jacobian` (https://github.com/JuliaDiff/AbstractDifferentiation.jl/blob/12a0e27d0f54e6300b725dfb9dafc21ef507b724/src/AbstractDifferentiation.jl#L567).

I think one "just" has to define `value_and_pullback_function` in terms of only `rrule` for these backends. This should avoid the unnecessary call of the original function.

**Comment by devmotion** [comment]
Just noticed, there's already #34, #35, #36.
